const DASHBOARD_LAYOUT_CHANGE = 'DASHBOARD_LAYOUT_CHANGE';
export { DASHBOARD_LAYOUT_CHANGE };

const DASHBOARD_CHANGE_WIDTH = 'DASHBOARD_CHANGE_WIDTH';
export { DASHBOARD_CHANGE_WIDTH };

const WIDGET_CHANGE_SIZE = 'WIDGET_CHANGE_SIZE';
export { WIDGET_CHANGE_SIZE };

const UI_WINDOW_RESIZE = 'UI_WINDOW_RESIZE';
export { UI_WINDOW_RESIZE };
