export const DASHBOARD_LAYOUT_CHANGE = 'DASHBOARD_LAYOUT_CHANGE';
export const DASHBOARD_CHANGE_WIDTH = 'DASHBOARD_CHANGE_WIDTH';

export const UI_WINDOW_RESIZE = 'UI_WINDOW_RESIZE';

export const WIDGET_ADD_WIDGET = 'WIDGET_ADD_WIDGET';
export const WIDGET_REMOVE_WIDGET = 'WIDGET_REMOVE_WIDGET';
export const WIDGET_CHANGE_CONTENT = 'WIDGET_CHANGE_CONTENT';
export const WIDGET_CHANGE_SIZE = 'WIDGET_CHANGE_SIZE';

export const DICE_WIDGET_ROLL = 'DICE_WIDGET_ROLL';
export const DICE_WIDGET_RESET = 'DICE_WIDGET_RESET';

export const NAV_MENU_TOGGLE = 'NAV_MENU_TOGGLE';
export const NAV_MENU_CLOSE = 'NAV_MENU_CLOSE';

export const RANFILTRATOR_WIDGET_RUN = 'RANFILTRATOR_WIDGET_RUN';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';

export const ACCOUNT_POPOVER_MENU = 'ACCOUNT_POPOVER_MENU';


// export const SUBJECT_ACTION_DIRECTOBJECT 
// export const SUBJECT_ACTION