const DASHBOARD_LAYOUT_CHANGE = 'DASHBOARD_LAYOUT_CHANGE';
export { DASHBOARD_LAYOUT_CHANGE };

const DASHBOARD_CHANGE_WIDTH = 'DASHBOARD_CHANGE_WIDTH';
export { DASHBOARD_CHANGE_WIDTH };

const UI_WINDOW_RESIZE = 'UI_WINDOW_RESIZE';
export { UI_WINDOW_RESIZE };

const WIDGET_ADD_WIDGET = 'WIDGET_ADD_WIDGET';
export { WIDGET_ADD_WIDGET };

const WIDGET_REMOVE_WIDGET = 'WIDGET_REMOVE_WIDGET';
export { WIDGET_REMOVE_WIDGET };

const WIDGET_CHANGE_CONTENT = 'WIDGET_CHANGE_CONTENT';
export { WIDGET_CHANGE_CONTENT };

const WIDGET_CHANGE_SIZE = 'WIDGET_CHANGE_SIZE';
export { WIDGET_CHANGE_SIZE };
